.github/workflows/ci.yml
tests/prospector_profile.yaml
uds/__init__.py
uds/messages/base_message.py
uds/messages/pdu.py
uds/messages/response.py
uds/messages/service_identifiers.py
uds/messages/types.py
uds/transport_interface/__init__.py
uds/transport_interface/client.py
uds/transport_interface/common.py
uds/transport_interface/server.py
uds/transport_interface/types.py

Provide module with abstract Transport Interfaces for handling layers 4-1 (OSI model) of UDS protocol.

Introduce abstract Transport Interfaces

---

.github/FUNDING.yml

Provide options for sponsoring.

Sponsoring

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
README.rst

This is first part of #53 - automated schedule is configured daily so the first result is there.
Unfortunately, we test on production (we are going to see whether it works or not after the merge).

Security scans

---

.readthedocs.yaml
README.rst
docs/source/conf.py

- updated shields on main page
- added LGTM config (shield on main page)
- ReadTheDocs failing builds fixed
- ReadTheDocs documentation builded - https://readthedocs.org/projects/uds/builds/14753739/
- local review

Main pasge shields + ReadTheDocs

---

docs/source/pages/message.rst
tests/software_tests/messages/test_uds_message.py
uds/messages/uds_message.py
uds/messages/uds_packet.py

- payload attribute added to AbstractUdsPacket
- payload attribute added to AbstractUdsPacketRecord
- UdsMessageRecord updated with packets` payload
- documentation updated
- software tests
- documentation build and review

Add payload attribute to Packets classes.

---

docs/source/pages/knowledge_base/diagnostic_message.rst
docs/source/pages/knowledge_base/packet.rst
docs/source/pages/knowledge_base/segmentation.rst
docs/source/pages/message.rst

- Create references to important knowledge base chapters.
- Add links in User Documentation.
- documentation build
- documentation review

Add knowledge base references.

---

.github/workflows/ci.yml
setup.cfg

Remove Python 3.6 from PyPi configuration.
Update ci.yml (dependency check).
- github actions
- review

Python 3.6 is not supported.

---

tests/software_tests/can/test_consecutive_frame.py
tests/software_tests/can/test_first_frame.py
tests/software_tests/can/test_flow_control.py
tests/software_tests/can/test_single_frame.py
tests/software_tests/message/test_uds_message.py
tests/software_tests/packet/test_can_packet.py
tests/software_tests/packet/test_can_packet_record.py
uds/can/addressing_information.py
uds/can/consecutive_frame.py
uds/can/first_frame.py
uds/can/flow_control.py
uds/can/frame_fields.py
uds/can/single_frame.py
uds/message/uds_message.py
uds/packet/__init__.py
uds/packet/abstract_packet.py
uds/packet/abstract_packet_type.py
uds/packet/can_packet.py
uds/packet/can_packet_record.py

- defective CAN Packet implementation
- bug fix for casual CAN Packets
- unit tests
- integrations tests (especially for previously found defect)

CAN Packet update

---

tests/software_tests/can/test_first_frame.py
tests/software_tests/packet/test_abstract_packet.py
tests/software_tests/packet/test_can_packet.py

Fix warnings reported by LGTM in tests and docs.
LGTM report review (also the tests and docs part)

Fix LGTM Warnings

---

tests/software_tests/transport_interface/test_abstract_transport_interface.py
uds/transport_interface/__init__.py
uds/transport_interface/abstract_transport_interface.py

Define API for Abstract Transport Interface.
- review

Transport Interface API

---

.github/FUNDING.yml
README.rst

Closes #199
- updated bades on the main page (README)
- left only one sponsoring option
GitHub Actions jobs

Main page and sponsoring update

---

.readthedocs.yaml
docs/requirements_for_docs.txt
docs/source/conf.py
pyproject.toml

Update requirements file for documentation to include missing library. 
Documentaiton was built on readthedocs portal directly from this branch.

Fix to failing documentation buils

---

tests/software_tests/can/test_mixed_addressing_information.py
tests/software_tests/can/test_normal_addressing_information.py
uds/can/mixed_addressing_information.py

Fix problems with tests (not all paths were reached anymore)/
- unit tests
- coverage checking

Quickfix for typing alias

---

docs/requirements_for_docs.txt

- Update requirements_for_docs.txt
- documentaiton was build on ReadTheDocs portal

ReadTheDocs bugfix

---

README.rst

Add information why people shall use this package.
- review

Documenation - Why this package

---

.codecov.yml
.github/workflows/testing.yml
tests/software_tests/transport_interface/test_can_transport_interface.py
uds/transport_interface/can_transport_interface.py

Add branch coverage measurement for unit and integration tests.
- measured values are shown on codecov page (https://app.codecov.io/gh/mdabrowski1990/uds/flags/branch-coverage-measurement)

Add branch coverage measurement

---

tests/software_tests/can/packet/test_first_frame.py
tests/software_tests/database/data_record/test_raw_data_record.py
tests/software_tests/database/data_record/test_text_data_record.py
uds/database/data_record/__init__.py
uds/database/data_record/abstract_data_record.py
uds/database/data_record/mapping_data_record.py
uds/database/data_record/raw_data_record.py
uds/database/data_record/text_data_record.py

Implementation for Text Data Records.
- CI
- unit tests
- integration tests

Text Data Record

---

tests/software_tests/test_uds.py
uds/__init__.py
uds/__init__.pyi
uds/can/transport_interface/common.py
uds/message/uds_message.py
uds/utilities/enums.py

- Lazy imports in `uds.__init__.py`
- Stub file defined `uds.__init__.pyi`
- manual importing and performance comparison

Introduce lazy imports and improve importing performance

---

docs/source/pages/knowledge_base/service.rst
tests/software_tests/client/test_client.py
uds/__init__.py
uds/__init__.pyi
uds/can/transport_interface/python_can.py
uds/client.py
uds/transport_interface/abstract_transport_interface.py

#5 
- Client class API defined
- client module added to project imports
- timeout parameter None value explained wherever used
- review

Define Client API

---

tests/software_tests/utilities/test_conversions.py
tests/software_tests/utilities/test_enums.py
uds/can/packet/can_packet.py
uds/can/packet/can_packet_record.py
uds/message/nrc.py
uds/message/service_identifiers.py
uds/message/uds_message.py
uds/packet/abstract_packet.py
uds/utilities/__init__.py
uds/utilities/common_types.py
uds/utilities/conversions.py
uds/utilities/enums.py

- Raw Bytes to Hex conversion implementation
- change error suppression for vulture
- slight rework of utilities sub-modules
- unit tests

Raw Bytes to Hex conversion

---

README.rst
pyproject.toml
uds/__init__.py

- bump version
- tiny building improvements
- pyroma

Release (3.0.0) - Client
